Update sp.json
AntiochTechnology/bible-reference-toolkit pull request #11
Opened 2023-10-03 21:12 UTC by oscampo

Added "two letter" short names to some books

2023-10-03 21:54 UTC, oscampo commented
Hi @tim-hub 
I added some short names on a common format on spanish ("two letter" short names), and tryed to merge, but I obtained an error, please could you check it ?

2023-10-03 23:05 UTC, tim-hub commented
It complains the duplication, break the unique constraint

2023-10-03 23:08 UTC, tim-hub commented on packages/bible-book-names-intl/src/data/translations/sp.json
> +    "shortNames": ["Job"
here, break the unique constraint.

2023-10-03 23:08 UTC, tim-hub requested changes
test failed because of book Job

2023-10-03 23:19 UTC, oscampo commented
> test failed because of book Job

ok.. fixed and updated

2023-10-04 19:38 UTC, tim-hub commented
closed this, https://github.com/AntiochTechnology/bible-reference-toolkit/pull/12

2023-10-04 19:38 UTC, closed without merging